<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<Version>0.0.1</Version>
	<AssemblyVersion>0.0.1</AssemblyVersion>
	<FileVersion>0.0.1</FileVersion>
	<UserSecretsId>99eaed63-cc5a-4495-9d7d-cfdaf098cdbb</UserSecretsId>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YetAnotherXiaomiCloudClient\YetAnotherXiaomiCloudClient.csproj" />
  </ItemGroup>

</Project>
